# Generated by Django 5.0.1 on 2024-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patient_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(upload_to='accounts/images/'),
        ),
    ]
