# Generated by Django 5.0.1 on 2024-01-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='meet_link',
        ),
    ]
